version: '3.1'
services: 
    web:
        build: 
            context: ./web
            dockerfile: ./Dockerfile
        ports: 
            - 8080:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
        volumes: 
            - "./web:/build/web"
            - "/build/web/node_modules"
        depends_on: 
            - server
        command: ["npm", "start"]

    server:
        build: 
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - 80:5000
        volumes: 
            - "./server:/build/server"
        depends_on: 
            - db
        command: ["python", "/build/server/application.py"]
    
    db:
        image: "mysql:8.0"
        ports:
            - 3306:3306
        volumes:
            - ./data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: uu_code_challenge
            MYSQL_ROOT_PASSWORD: password
            MYSQL_INITDB_SKIP_TZINFO:
